[default]
db_host = "localhost"
db_name = "axum_demo"
db_password = "mysecretpassword"
db_username = "postgres"

[test]
log_level = "warn,axum_demo::config=error"

[cloud]
db_host = "postgres"
redis_url = "redis://redis:6379"

# TODO configmap
