[default]
database_url = "postgres://postgres:mysecretpassword@localhost/axum_demo"

[test]
log_level = "warn,utils::config::config=error"

[cloud]
database_url = "postgres://postgres:mysecretpassword@postgres/axum_demo"
