[test]
log_level = "warn,utils::config::app=error"

[local]
database_url = "postgres://postgres:mysecretpassword@localhost/axum_demo"

[cloud]
database_url = "postgres://postgres:mysecretpassword@postgres/axum_demo"
