# Based on example available at:
# https://github.com/GoogleContainerTools/skaffold/tree/main/examples/multi-config-microservices

apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: microverse
requires:
- path: ./storage
- path: ./migrate-db
- path: ./axum-demo
