# kubectl create job migrate-db --image=rust:1.60 --dry-run=client -o yaml > migrate-db/k8s/migrate-db-job.yaml

apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-db
spec:
  backoffLimit: 4 # try job 5 times
  template:
    spec:
      volumes:
      - name: config
        configMap:
          name: app-config
          items:
          - key: application.toml
            path: application.toml
      containers:
      - image: andregs/migrate-db
        name: migrate-db
        env:
        - name: RUST_BACKTRACE
          value: "1"
        - name: APP_PROFILE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: app_profile
              optional: true
        - name: APP_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        volumeMounts:
        - name: config
          mountPath: /app/config/base
          readOnly: true

      # pod's container will not be restarted upon failure, but
      # will result in a new pod for the job until backoffLimit
      restartPolicy: Never

