apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: migrate-db
build:
  artifacts:
  - image: andregs/migrate-db
    context: ..
    docker:
      dockerfile: ./migrate-db/Dockerfile
      cacheFrom:
      - "rust:1.60.0"
      - "lukemathwalker/cargo-chef:latest-rust-1.60.0"
      - "andregs/axum-demo"
      - "andregs/migrate-db"
deploy:
  kubectl:
    manifests:
    - ./k8s/*.yaml
    