apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: migrate-db
requires:
- path: ../rust-builder
build:
  artifacts:
  - image: andregs/migrate-db
    context: ..
    requires:
    - image: andregs/rust-builder
      alias: BASE
    docker:
      dockerfile: ./migrate-db/Dockerfile
      cacheFrom:
      - andregs/rust-builder
deploy:
  kustomize:
    paths:
    - ./k8s/default
profiles:
- name: cloud
  deploy:
    kustomize:
      paths:
      - ./k8s/cloud
