apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: axum-demo
requires:
- path: ../rust-builder
build:
  artifacts:
  - image: andregs/axum-demo
    context: ..
    requires:
    - image: andregs/rust-builder
      alias: BASE
    docker:
      dockerfile: ./axum-demo/Dockerfile
      cacheFrom:
      - andregs/rust-builder
deploy:
  kustomize:
    paths:
    - ./k8s/local-cluster
#profiles:
#- name: test
#  deploy:
#    kustomize:
#      paths:
#      - ./k8s/test
portForward:
- resourceType: service
  resourceName: axum-demo
  port: 3000

# TODO perhaps I can change the default profile from 'local-cluster' to 'default'
# and then use the default to spin up storage and execute tests locally (not on cloud)
# and execute the app locally too, with migrations and everything
