apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: storage
deploy:
  kustomize:
    paths:
    - ./k8s/local-cluster
portForward:
- resourceType: service
  resourceName: postgres
  port: 5432
- resourceType: service
  resourceName: redis
  port: 6379
