# app configuration
# sensible defaults are hard-coded in axum_demo::config::Config
# the following profiles override such defaults

[default]
db_password = "mysecretpassword"
db_username = "postgres"

[test]
log_level = "warn"

[cloud]
db_host = "postgres"
redis_url = "redis://redis:6379"
