# kubectl create deployment axum-demo --image=andregs/axum-demo --dry-run=client -o yaml > axum-demo/k8s/axum-demo-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: axum-demo
  name: axum-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: axum-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: axum-demo
    spec:
      containers:
      - image: andregs/axum-demo
        name: axum-demo
        resources: {}
        env:
        - name: RUST_BACKTRACE
          value: "1"
        - name: APP_PROFILE
          value: cloud
status: {}