# kubectl create deployment axum-demo --image=andregs/axum-demo --dry-run=client -o yaml > axum-demo/k8s/axum-demo-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: axum-demo
  name: axum-demo
spec:
  selector:
    matchLabels:
      app: axum-demo
  template:
    metadata:
      labels:
        app: axum-demo
    spec:
      volumes:
      - name: config
        configMap:
          name: app-config
          items:
          - key: application.toml
            path: application.toml
      containers:
      - image: andregs/axum-demo
        name: axum-demo
        env:
        - name: RUST_BACKTRACE
          value: "1"
        - name: APP_PROFILE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: app_profile
              optional: true
        - name: APP_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        volumeMounts:
        - name: config
          mountPath: /app/config/base
          readOnly: true
