apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: web
build:
  artifacts:
  - image: andregs/axum-demo
    context: ..
    docker:
      dockerfile: ./web/Dockerfile
      cacheFrom:
      - "rust:1.60.0"
      - "lukemathwalker/cargo-chef:latest-rust-1.60.0"
      - "andregs/axum-demo"
      - "andregs/migrate-db"
deploy:
  kubectl:
    manifests:
    - ./k8s/*.yaml
portForward:
- resourceType: service
  resourceName: axum-demo
  port: 3000
