apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: web
build:
  artifacts:
  - image: andregs/axum-demo
    docker:
      dockerfile: ./web/Dockerfile
  local: 
    useDockerCLI: false
    useBuildkit: false
deploy:
  kubectl:
    manifests:
    - ./k8s/*.yaml
portForward:
- resourceType: service
  resourceName: axum-demo
  port: 3000
